title:             Gyuho's blog
email:             kwon920612@gmail.com
description:       냉무
author:            Gyuho Kwon
baseurl:           "/kwon1148.github.io"
url:               "http://kwon1148.github.io"

# Social Profiles
twitter_username:  SBootstrap
github_username:   BlackrockDigital
facebook_username: StartBootstrap

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
